export const POST_REQUEST = "POST_REQUEST";
export const POST_ERROR = "POST_ERROR";
export const POST_SUCCESS = "POST_SUCCESS";
export const FETCH_SUCCESS = "FETCH_SUCCESS";

export const RESET_POST_STATE = "RESET_POST_STATE";
