# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - name: yarn install, lint, and test
        run: |
          yarn
          yarn run lint:js
          yarn run lint:format:check
          yarn run test:ci:all

      - name: Add Heroku Remote Origin
        run:
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_TOKEN
          }}@git.heroku.com/${{ secrets.HEROKU_BACKEND_APP_NAME }}.git
      - name: Split the packages/api subtree
        run: git subtree split --prefix packages/api -b split
      - name: Deploy API to Heroku
        run: git push -f heroku split:main
